services:
  - type: web
    name: adhikar-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn adhikar.backend.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11
